### ISSUE TITLE
Generate directories to mirror target directory structure

### ISSUE THREAD

**Issue by pcasaretto** [mozy/ruby-protocol-buffers#11]
Hmm... couldn't figure out a better title.

I expected the following 

```
$ ruby-protoc directory/sub/test.proto
```

to generate

/directory/sub/test.pb.rb

"regular" protoc works this way.

Reasonable?
Ill be happy to fork and try to solve this if you think it should be done.

**Comment by codekitchen** [comment]
Yeah that'd be great.

I see weird behavior with `protoc` when the first level of target folder exists, but not the sub-folders -- if you want to error or auto-create the folders, I'm fine with either solution.

btw if it's not painfully obvious already, most of people's current usage of ruby-protocol-buffers has been with projects that use one monolithic `.proto` file for everything. :)
