### ISSUE TITLE
Message initialization initializes optional nested messages

### ISSUE THREAD

**Issue by ghost** [mozy/ruby-protocol-buffers#23]
Using this .proto file:

```
message Foo {}
message Bar {
    optional Foo foo = 1;
}
```

I would expect `Bar.new.foo` to be `nil`, but it is actually a `Foo` instance.

This also causes deserialization of messages with empty optional fields to be non-empty.

**Comment by codekitchen** [comment]
How are you defining "non-empty"? You check if a field is present by calling `obj.has_<field>?` not by accessing the field, so in this case you want `Bar.new.has_foo?` , or `Bar.parse('').has_foo?` , both of which will return false.

See the "Singular Message Fields" documentation section of http://rubydoc.info/gems/ruby-protocol-buffers/1.2.2/ProtocolBuffers/Message

**Comment by ghost** [comment]
I see. I was using `Bar.parse('').inspect` and saw all fields having instances (with `Bar` being a message having many optional fields), so I assumed they were all present.

**Comment by codekitchen** [comment]
oho, good catch. I'd call that a bug in Message#inspect, it shouldn't print out the placeholder value of the field if it's not set.
